name: Build Font

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get update 
          sudo apt-get install fontmake fonttools -y
      - name: Build
        run: |
          ./build-ttf.sh
          ./build-woff.sh
          ./build-woff2.sh
          ./build-subsets.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact.zip
          path: 'build/'
          
